### PR TITLE
chore: migrate vitest to node:test

### PR DESCRIPTION
**Pull request by mateonunez**
# Pull Request
Compile all the information written below to send a legitimate pull request to the repository.

### This PR is labeled as:
*Choose only one and remember to select the label even on the right.*

- [ ] Feature
- [ ] Bug
- [x] Other

### This PR has the following linked issues:
- Doesn't close any issues.

### My solution is explained as follows:

I noticed that this repo used `vitest` (I love it). This PR aims to remove this dependency in favor of the `node:test` module. I think we can improve this repository by avoiding external dependencies as much as possible. wdyt?

For the coverage there are 2 ways: 
- Use the `--experimental-test-coverage` flag
- Install c8, which is the native V8 code-coverage.

I tried both, but chose the second one (also used in my projects).

### CODE REVIEW

**Review by airscripts — APPROVED** [review]
I love this! Thank you kindly @mateonunez, really appreciate it.  
I'm approving it, but not merging right now because I want to make a test run later just to get my hands off this.

**Comment by mateonunez** [comment]
> I love this! Thank you kindly @mateonunez, really appreciate it.  
> 
> I'm approving it, but not merging right now because I want to make a test run later just to get my hands off this.

Nice! After this PR will be merged I could add the CI to perform tests in pipeline.

**Comment by airscripts** [comment]
> That would be amazing! I was literally ashamed to see that I missed to add that here.

Nevermind, I've seen that there's CircleCI here.
Maybe we can adapt that directly in this PR.

**Comment by mateonunez** [comment]
Now CircleCI should run the correct command, @airscripts

**Comment by airscripts** [comment]
I've made the run that I've anticipated to you yesterday @mateonunez.  
Before merging this I have to migrate the project to Node v20, since in v18 it's not working and some tests are failing.  
No problem though, I don't think it will be hard, I imagine that everything will work just bumping the version up.

**Comment by mateonunez** [comment]
> Before merging this I have to migrate the project to Node v20, since in v18 it's not working and some tests are failing.

That's weird... locally tests are passing with Node v18. Sigh...

image

Do you have any logs?

**Comment by airscripts** [comment]
> That's weird... locally tests are passing with Node v18. Sigh...
> 
> image
> Do you have any logs?

I have retested this using the latest v18 and everything works right.
Nevermind!

Thank you kindly for your contribution, totally appreciate it from my deepest.

**Pull request merged**
